language: node_js
os: linux
dist: xenial
node_js:
  - "14.17.6"
cache:
  directories:
    - ".meteor"
    - ".babel-cache"
script:
  - travis_retry ./packages/test-in-console/run.sh
env:
  global:
    - CXX=g++-4.8
    - phantom=false
    - PUPPETEER_DOWNLOAD_PATH=~/.npm/chromium
    - IGNORE_ASYNC_PLUGIN=1
  jobs:
    # Disable fibers for all jobs
    - DISABLE_FIBERS=1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
