language: node_js
os: linux
dist: jammy
node_js:
  - "18.16.0"
cache:
  directories:
    - ".meteor"
    - ".babel-cache"
script:
  - travis_retry ./packages/test-in-console/run.sh
env:
  global:
    - CXX=g++-12
    - phantom=false
    - PUPPETEER_DOWNLOAD_PATH=~/.npm/chromium
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-12
      - libnss3

before_install:
  - cat /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install -y python3.8 python3.8-distutils
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
  - python3 --version
  - sudo add-apt-repository --yes "deb http://archive.ubuntu.com/ubuntu jammy main universe"
  - sudo apt-get update
  - sudo apt-get install -y libnss3
