language: node_js
os: linux
dist: xenial
node_js:
  - "14.21.2"
cache:
  directories:
    - ".meteor"
    - ".babel-cache"
script:
  - travis_retry ./packages/test-in-console/run.sh
env:
  global:
    - CXX=g++-4.8
    - phantom=false
    - PUPPETEER_DOWNLOAD_PATH=~/.npm/chromium
    # Disable fibers for all jobs
    - DISABLE_FIBERS=1
    - IGNORE_ASYNC_PLUGIN=1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libnss3

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade -y libnss3
