name: Meteor Selftest Cordova

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - devel
      - 2.x.x

env:
  # This multiplier scales the waitSecs for selftests.
  TIMEOUT_SCALE_FACTOR: 8

  # Retry failed tests additional times.
  METEOR_SELF_TEST_RETRIES: 2

  # These, mostly overlapping, flags ensure that CircleCI is as pretty as
  # possible for a non-interactive environment.  See also: --headless.
  METEOR_HEADLESS: true
  METEOR_PRETTY_OUTPUT: 0

  # In an effort to stop SIGSEGV, this just doesn't bother cleaning up
  # the mess of temp directories that Meteor makes.
  METEOR_SAVE_TMPDIRS: 1

  # Skip these tests on every test run.
  # If needed, for readability this should be a regex wrapped across
  # multiple lines in quotes.
  SELF_TEST_EXCLUDE: "add debugOnly and prodOnly packages"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: meteor/circleci:2024.09.9-android-34-node-20
      options: --entrypoint "/bin/bash"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test Cordova
        run: |
          java --version
          gradle --version
          ./meteor self-test ^cordova
