name: Meteor Selftest Windows

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - release-3.0
  push:
    branches:
      - release-3.0

env:
  METEOR_PRETTY_OUTPUT: 0
  SELF_TEST_TOOL_NODE_FLAGS: ' '
  TOOL_NODE_FLAGS: --expose-gc
  TIMEOUT_SCALE_FACTOR: 8
  METEOR_HEADLESS: true
  SELF_TEST_EXCLUDE: '^NULL-LEAVE-THIS-HERE-NULL$'

jobs:
  test:
    runs-on: windows-2019

    strategy:
      matrix:
        platform:
          - x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: |
          .\scripts\windows\appveyor\install.ps1

      - name: Run tests
        run: |
          .\scripts\windows\appveyor\test.ps1

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            .\dev_bundle
            .\.babel-cache
            .\.meteor
          key: ${{ runner.os }}-meteor-${{ hashFiles('**/package-lock.json') }}
